[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
cargo = { target = "armv7a-unknown-xous-elf", allTargets = false, targetDir = "target/rust-analyzer" }
procMacro = { enable = true }
check = { workspace = false, allTargets = false, targets = [
  "armv7a-unknown-xous-elf",
] }
diagnostics = { disabled = ["unresolved-proc-macro"] }

[[language]]
name = "slint"
language-servers = ["slint-lsp"]
auto-format = true

[language-server.slint-lsp]
command = "slint-lsp"
args = ["-L", "ui=ui/ui"]
