inherits = "ashen"

"comment" = { fg = "g_6" }
"comment.block.documentation" = { fg = "g_5" }
"comment.line.documentation" = { fg = "g_5" }

"type" = "g_3"
"type.builtin" = "orange_glow"
"constant.builtin" = "orange_blaze"
"variable.builtin" = "g_2"

"variable.parameter" = { fg = "g_2" }
"keyword.directive" = { fg = "red_ember" }
"keyword.storage.modifier" = { fg = "red_ember" }

"function.builtin" = { fg = "g_3", modifiers = ["bold"] }

"tag" = { fg = "orange_glow" }

"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "red_glowing", modifiers = ["underlined"] }
"markup.quote" = { modifiers = ["italic"] }

"ui.virtual.inlay-hint" = { fg = "g_6" }
