"attribute" = "yellow_cooler"
"comment" = { fg = "yellow_faint" }
"constant" = { fg = "cyan" }
"constant.builtin" = { fg = "cyan" }
"constant.character.escape" = { fg = "green" }
"constant.numeric" = "cyan"
"constructor" = { fg = "green_cooler" }
"function" = { fg = "green_warmer" }
"function.builtin" = "green_warmer"
"function.macro" = "green_warmer"
"keyword" = { fg = "yellow" }
"label" = "yellow_cooler"
"module" = "yellow_cooler"
"namespace" = "yellow_cooler"
"operator" = "fg_main"
"punctuation" = "fg_main"
"special" = "magenta_cooler"
"string" = "red_warmer"
"tag" = "yellow_cooler"
"type" = "green_cooler"
"type.builtin" = "green_cooler"
"variable" = "cyan_cooler"
"variable.builtin" = "yellow_warmer"
"variable.other.member" = "cyan_cooler"
"variable.parameter" = "green_faint"

"diff.delta" = "yellow"
"diff.minus" = "red"
"diff.plus" = "green"

"error" = "red_warmer"
"hint" = "fg_dim"
"info" = "green"
"warning" = "yellow_warmer"

"ui.background" = { bg = "bg_main" }
"ui.cursor.match" = { bg = "bg_paren_match", fg = "fg_main" }
"ui.cursor.primary" = { bg = "cursor", fg = "bg_main" }
"ui.cursorline" = { bg = "bg_hl_line" }
"ui.help" = { bg = "bg_alt", fg = "fg_main" }
"ui.linenr" = { fg = "fg_dim" }
"ui.linenr.selected" = { fg = "fg_main" }
"ui.menu" = { fg = "fg_main", bg = "bg_alt" }
"ui.menu.selected" = { fg = "fg_main", bg = "bg_completion", modifiers = ["bold"] }
"ui.popup" = { bg = "bg_alt" }
"ui.selection" = { bg = "bg_paren_match" }
"ui.selection.primary" = { bg = "bg_region" }
"ui.statusline" = { fg = "fg_mode_line_active", bg = "bg_mode_line_active" }
"ui.statusline.inactive" = { fg = "fg_main", bg = "bg_inactive" }
"ui.statusline.insert" = { fg = "bg_main", bg = "green" }
"ui.statusline.normal" = { fg = "fg_mode_line_active", bg = "bg_mode_line_active" }
"ui.statusline.select" = { fg = "bg_main", bg = "blue" }
"ui.text" = { fg = "fg_main" }
"ui.text.focus" = { fg = "yellow" }
"ui.virtual" = { fg = "fg_dim" }
"ui.virtual.indent-guide" = { fg = "border" }
"ui.virtual.inlay-hint" = { fg = "fg_dim" }
"ui.virtual.ruler" = { bg = "bg_alt" }
"ui.virtual.whitespace" = "border"
"ui.window" = { fg = "border" }

"ui.bufferline.background" = { fg = "fg_main", bg = "bg_active" }
"ui.bufferline" = { fg = "fg_main", bg = "bg_active" }
"ui.bufferline.active" = { fg = "fg_main", bg = "bg_main" }

"diagnostic.error" = { underline = { color = "red_warmer", style = "double_line" } }
"diagnostic.hint" = { underline = { color = "fg_dim", style = "double_line" } }
"diagnostic.info" = { underline = { color = "green", style = "double_line" } }
"diagnostic.warning" = { underline = { color = "yellow_warmer", style = "double_line" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.text" = "yellow"
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.raw" = "red"
"markup.strikethrough" = { modifiers = ["crossed_out"] }

[palette]
bg_main = "#fff6d8"
bg_dim = "#f5e9cb"
bg_alt = "#e7d7c6"
bg_active = "#c7b7a6"
bg_mode_line_active = "#d9b15f"
bg_inactive = "#f9efd4"
bg_completion = "#ffe2a8"
bg_hover = "#deb4f0"
bg_hl_line = "#fae7b0"
bg_paren_match = "#afcf8f"
bg_region = "#f0d4d8"
border = "#c5baa6"
cursor = "#a07f00"
fg_main = "#484431"
fg_dim = "#68708a"
fg_alt = "#80431a"
fg_mode_line_active = "#403328"

red = "#ba2d2f"
red_warmer = "#c74400"
yellow = "#a26310"
yellow_warmer = "#ba5205"
yellow_cooler = "#946830"
yellow_faint = "#7f6f1a"
green = "#007a0a"
green_warmer = "#5a7400"
green_cooler = "#008250"
green_faint = "#61756c"
cyan = "#3f60af"
cyan_cooler = "#0f708a"
blue = "#375cc6"
magenta_cooler = "#6448ca"
