version = 1
default_mode = "desktop"
mode_switch_haptic = { type = "sweep", start_frequency = 400, end_frequency = 850, duration_ms = 65, gain = 0 }

[trackpad]
click_pressure = 25

[osk.bind]
l4 = "super"
l5 = "shift"
r4 = "control"
r5 = "alt"
left-trigger-click = "shift"
right-trigger-click = "enter"
x = "backspace"
y = "space"
dpad-up = "up"
dpad-down = "down"
dpad-left = "left"
dpad-right = "right"

[[global.bind]]
chord = ["steam", "x"]
action = { type = "keyboard-toggle" }

[[global.bind]]
chord = ["steam", "quick-access"]
action = { type = "mode-next" }

[mode.desktop]
gamepad = "none"

[[mode.desktop.bind]]
input = "l4"
action = { type = "key", key = "super" }

[[mode.desktop.bind]]
input = "r4"
action = { type = "key", key = "control" }

[[mode.desktop.bind]]
input = "l5"
action = { type = "key", key = "shift" }

[[mode.desktop.bind]]
input = "r5"
action = { type = "key", key = "alt" }

[[mode.desktop.bind]]
input = "dpad-up"
action = { type = "key", key = "up" }

[[mode.desktop.bind]]
input = "dpad-down"
action = { type = "key", key = "down" }

[[mode.desktop.bind]]
input = "dpad-left"
action = { type = "key", key = "left" }

[[mode.desktop.bind]]
input = "dpad-right"
action = { type = "key", key = "right" }

[[mode.desktop.bind]]
input = "left-trigger-click"
action = { type = "mouse", button = "right" }

[[mode.desktop.bind]]
input = "right-trigger-click"
action = { type = "mouse", button = "left" }

[[mode.desktop.bind]]
input = "right-pad-click"
action = { type = "mouse", button = "left" }

[[mode.desktop.bind]]
input = "left-pad-click"
action = { type = "mouse", button = "middle" }

[[mode.desktop.bind]]
input = "a"
action = { type = "key", key = "enter" }

[[mode.desktop.bind]]
input = "b"
action = { type = "key", key = "escape" }

[[mode.desktop.bind]]
input = "x"
action = { type = "key", key = "g" }

[[mode.desktop.bind]]
input = "y"
action = { type = "key", key = "space" }

[[mode.desktop.bind]]
input = "menu"
action = { type = "key", key = "tab" }

[[mode.desktop.bind]]
input = "view"
action = { type = "mouse", button = "back" }

[mode.desktop.layer.apps]
hold = "left-bumper"

[[mode.desktop.layer.apps.bind]]
input = "b"
action = { type = "key", key = "q" }

[[mode.desktop.layer.apps.bind]]
input = "x"
action = { type = "key", key = "t" }

[[mode.desktop.layer.apps.bind]]
input = "y"
action = { type = "key", key = "o" }

[[mode.desktop.axis]]
source = "right-pad"
target = "mouse-motion"
sensitivity = 150.0
acceleration = 1.75
deadzone = 0.0015

[[mode.desktop.axis]]
source = "left-pad"
target = "scroll"
sensitivity = 5.0
invert_y = true

[mode.game]
gamepad = "xbox"

[[mode.game.bind]]
input = "a"
action = { type = "gamepad", button = "south" }

[[mode.game.bind]]
input = "b"
action = { type = "gamepad", button = "east" }

[[mode.game.bind]]
input = "x"
action = { type = "gamepad", button = "west" }

[[mode.game.bind]]
input = "y"
action = { type = "gamepad", button = "north" }

[[mode.game.bind]]
input = "left-bumper"
action = { type = "gamepad", button = "left-bumper" }

[[mode.game.bind]]
input = "right-bumper"
action = { type = "gamepad", button = "right-bumper" }

[[mode.game.bind]]
input = "view"
action = { type = "gamepad", button = "select" }

[[mode.game.bind]]
input = "menu"
action = { type = "gamepad", button = "start" }

[[mode.game.bind]]
input = "l3"
action = { type = "gamepad", button = "left-stick" }

[[mode.game.bind]]
input = "r3"
action = { type = "gamepad", button = "right-stick" }

[[mode.game.bind]]
input = "dpad-up"
action = { type = "gamepad", button = "dpad-up" }

[[mode.game.bind]]
input = "dpad-down"
action = { type = "gamepad", button = "dpad-down" }

[[mode.game.bind]]
input = "dpad-left"
action = { type = "gamepad", button = "dpad-left" }

[[mode.game.bind]]
input = "dpad-right"
action = { type = "gamepad", button = "dpad-right" }

[[mode.game.bind]]
input = "l4"
action = { type = "gamepad", button = "west" }

[[mode.game.bind]]
input = "l5"
action = { type = "gamepad", button = "south" }

[[mode.game.bind]]
input = "r4"
action = { type = "gamepad", button = "north" }

[[mode.game.bind]]
input = "r5"
action = { type = "gamepad", button = "east" }

[[mode.game.axis]]
source = "left-stick"
target = "gamepad-left-stick"
deadzone = 0.12

[[mode.game.axis]]
source = "right-stick"
target = "gamepad-right-stick"
deadzone = 0.12

[[mode.game.axis]]
source = "right-pad"
target = "mouse-motion"
sensitivity = 250.0
acceleration = 5.0
deadzone = 0.0015

# [[mode.game.axis]]
# source = "gyro"
# target = "mouse-motion"
# activation = { all = ["left-grip-touch", "right-grip-touch"] }
# components = ["y", "x"]
# deadzone = 0.02
# sensitivity = 600.0
# invert_x = true
# invert_y = true

[[mode.game.axis]]
source = "left-trigger"
target = "gamepad-left-trigger"

[[mode.game.axis]]
source = "right-trigger"
target = "gamepad-right-trigger"
